### ISSUE TITLE
Possible without root package.json having expo/react/react-native?

### ISSUE THREAD

**Issue by ecoleman** [Fried-Chicken/expo-monorepo#2]
It is possible to make this work without requiring the root installation of expo/react/react-native? I'd rather not repeat the dependencies in the root package.json, but it appears to cause issues with metro

**Comment by codebutler** [comment]
Is there any solution using `nohoist`? https://yarnpkg.com/blog/2018/02/15/nohoist/

**Comment by Fried-Chicken** [comment]
@codebutler You can turn yarn workspaces off entirely and then use `lerna bootstrap` to do the symlinking of the packages. That should work.

**Comment by codebutler** [comment]
I tried this but it breaks all the yarn commands 😩
https://github.com/yarnpkg/yarn/issues/3973

**Comment by Slapbox** [comment]
I'm also very interested in this. Can anyone else mention the OS they're using just for reference? I'm using Windows, so I fully expect to never get this working, but I expect it's at least possible on Linux or Mac.

**Comment by Fried-Chicken** [comment]
@codebutler You could always cd into the directory an run the yarn commands, that should work.

**Comment by Slapbox** [comment]
@Fried-Chicken actually that's what I have to do, but unfortunately `react-native` is still required in the root `package.json`

Perhaps this can be fixed with the following. I've not tested it:

**App.json**
Change:
```js
    "rnCliPath" : "../../node_modules/react-native/local-cli/cli.js",
```
to:
```
    "rnCliPath" : "./node_modules/react-native/local-cli/cli.js",
```

**Comment by Slapbox** [comment]
I'm going to bet this commit to `expo-cli` will go a long way towards allowing this: https://github.com/expo/expo-cli/commit/140a27f37d7e7ff353eb6a043d8fad811df521c9

**Comment by Fried-Chicken** [comment]
Hey @slapbox That looks like it’ll fix the problem! Let’s reopen this issue and see if we can fix this issue. Will probably take a week or two as I don’t have my personal laptop with me this week. Unless one of you guys can raise a pr that fixes it!

**Comment by Fried-Chicken** [comment]
Made a few attempts to get this to work. Was unable to get it working properly. There appears to be issues with symlinks not being supported by watchman. This has been raised as an issue [here](
https://github.com/facebook/watchman/issues/105) Closing issue as it’s not currently possible to move the dependencies from the root package.jaon.

**Comment by Fried-Chicken** [comment]
@Slapbox I didn't commit any of the code, so I don't have any of it, but I would say none of it was close at all. I'm using Mac by the way.

**Comment by Slapbox** [comment]
@Fried-Chicken thanks for the update anyway and thanks for all the work you've done!

If I get around to trying to make this work on Windows I'll post my findings.

**Comment by Fried-Chicken** [comment]
@Slapbox No worries. If you do manage to get it working, I would be more than happy to review the PR. It would be very interesting to see how the problem was tackled.
