### ISSUE TITLE
Thank you for this repo!

### ISSUE THREAD

**Issue by Slapbox** [Fried-Chicken/expo-monorepo#3]
Finding information on how to set up a `lerna` / `react-native` monorepo proved to be very difficult. This repo is a godsend. Thank you @Fried-Chicken!

10/10 - Would let emoji dictate my life again.

**Comment by Fried-Chicken** [comment]
Hey @Slapbox,

Glad you like the repo. I agree, unfortunately there isn't much information out there which is a shame because this is the perfect use case for a monorepo. Hoping to help others our by shedding some light on this. 

😈 "Ahh, so we meet again @Slapbox" ~ emoji
