### ISSUE TITLE
Doesn't work with latest expo sdk (32.0.0)

### ISSUE THREAD

**Issue by lnmunhoz** [Fried-Chicken/expo-monorepo#5]
I've tried to update to the latest sdk but it seems that it doesn't map the modules folder correctly. The error message is:

```
Unable to resolve "expo" from "index.js"
```

Any idea how to fix?

**Update**

Maybe this is relevant for fixing this issue: https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces

**Comment by Fried-Chicken** [comment]
Hi @lnmunhoz 

Not sure how to fix this as I haven't tried it yet.
Looks like the link you added might work, any luck so far?

@Fried-Chicken

**Comment by D3CK3R** [comment]
@lnmunhoz any luck so far with the update? We're try to solve this issue since 8 hours :-)

**Comment by lnmunhoz** [comment]
@D3CK3R Yes! What I've done was to add [this package](https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces) to my monorepo and follow the instructions.

Let me know if it works for you. Cheers!

**Comment by lnmunhoz** [comment]
@andybastian Yes I did. I don't know if I was clear, but you should clone and add this folder to your project, don't install the dev dependency because its outdated. That's the exact error I got as well.

If you put that folder in your project and configure yarn workspaces correctly it should work :)

**Comment by andybastian** [comment]
@lnmunhoz Thank you very much! :) Now it works. Had to add the folder to the project as you described.

**Comment by Fried-Chicken** [comment]
@andybastian @lnmunhoz, Good that you guys found a solution for this. Any chance one of you could raise a PR for this fix so others can also use it?

**Comment by lnmunhoz** [comment]
@Fried-Chicken I can submit the fix next week 👍

**Comment by Fried-Chicken** [comment]
@lnmunhoz Thanks a lot, much appreciated!

**Comment by lnmunhoz** [comment]
#7

**Comment by Fried-Chicken** [comment]
Merged so closing.
